### ISSUE TITLE
Initial iPhone App Release

### ISSUE THREAD

**Issue by byndcivilization** [advisorconnect/advisorconnect-roadmap#27]
## Your Environment

* app environment:
	- [ ] develop.advisorconnect.co
	- [ ] staging.advisorconnect.co
	- [ ] demo.advisorconnect.co
	- [ ] app.advisorconnect.co
* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by ArtyEmsee** [comment]
This has been completed: https://itunes.apple.com/us/app/advisorconnectapp/id1283345537?mt=8
